/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceRouteImport } from './routes/_workspace'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AssessorRouteImport } from './routes/assessor'
import { Route as EcriRouteImport } from './routes/ecri'
import { Route as LoginRouteImport } from './routes/login'
import { Route as WorkspaceEvidenceRouteImport } from './routes/_workspace.evidence'
import { Route as WorkspaceIntelligenceRouteImport } from './routes/_workspace.intelligence'
import { Route as WorkspaceOrientationRouteImport } from './routes/_workspace.orientation'
import { Route as WorkspaceOverviewRouteImport } from './routes/_workspace.overview'
import { Route as WorkspaceProfileRouteImport } from './routes/_workspace.profile'
import { Route as WorkspacePulseRouteImport } from './routes/_workspace.pulse'
import { Route as AssessorIndexRouteImport } from './routes/assessor.index'
import { Route as AssessorIdRouteImport } from './routes/assessor.$id'
import { Route as WorkspaceAssessmentIndexRouteImport } from './routes/_workspace.assessment.index'
import { Route as WorkspaceAssessmentDomainRouteImport } from './routes/_workspace.assessment.$domain'
import { Route as AssessorIdIndexRouteImport } from './routes/assessor.$id.index'
import { Route as AssessorIdContextRouteImport } from './routes/assessor.$id.context'
import { Route as AssessorIdEvidenceRouteImport } from './routes/assessor.$id.evidence'
import { Route as AssessorIdResponsesRouteImport } from './routes/assessor.$id.responses'
import { Route as AssessorIdRunsRouteImport } from './routes/assessor.$id.runs'
import { Route as AssessorIdScoringRouteImport } from './routes/assessor.$id.scoring'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessorRoute = AssessorRouteImport.update({
  id: '/assessor',
  path: '/assessor',
  getParentRoute: () => rootRouteImport,
} as any)
const EcriRoute = EcriRouteImport.update({
  id: '/ecri',
  path: '/ecri',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceEvidenceRoute = WorkspaceEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceIntelligenceRoute = WorkspaceIntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceOrientationRoute = WorkspaceOrientationRouteImport.update({
  id: '/orientation',
  path: '/orientation',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceOverviewRoute = WorkspaceOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceProfileRoute = WorkspaceProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspacePulseRoute = WorkspacePulseRouteImport.update({
  id: '/pulse',
  path: '/pulse',
  getParentRoute: () => WorkspaceRoute,
} as any)
const AssessorIndexRoute = AssessorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AssessorRoute,
} as any)
const AssessorIdRoute = AssessorIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AssessorRoute,
} as any)
const WorkspaceAssessmentIndexRoute =
  WorkspaceAssessmentIndexRouteImport.update({
    id: '/assessment/',
    path: '/assessment/',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceAssessmentDomainRoute =
  WorkspaceAssessmentDomainRouteImport.update({
    id: '/assessment/$domain',
    path: '/assessment/$domain',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const AssessorIdIndexRoute = AssessorIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AssessorIdRoute,
} as any)
const AssessorIdContextRoute = AssessorIdContextRouteImport.update({
  id: '/context',
  path: '/context',
  getParentRoute: () => AssessorIdRoute,
} as any)
const AssessorIdEvidenceRoute = AssessorIdEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => AssessorIdRoute,
} as any)
const AssessorIdResponsesRoute = AssessorIdResponsesRouteImport.update({
  id: '/responses',
  path: '/responses',
  getParentRoute: () => AssessorIdRoute,
} as any)
const AssessorIdRunsRoute = AssessorIdRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => AssessorIdRoute,
} as any)
const AssessorIdScoringRoute = AssessorIdScoringRouteImport.update({
  id: '/scoring',
  path: '/scoring',
  getParentRoute: () => AssessorIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assessor': typeof AssessorRouteWithChildren
  '/ecri': typeof EcriRoute
  '/login': typeof LoginRoute
  '/evidence': typeof WorkspaceEvidenceRoute
  '/intelligence': typeof WorkspaceIntelligenceRoute
  '/orientation': typeof WorkspaceOrientationRoute
  '/overview': typeof WorkspaceOverviewRoute
  '/profile': typeof WorkspaceProfileRoute
  '/pulse': typeof WorkspacePulseRoute
  '/assessor/$id': typeof AssessorIdRouteWithChildren
  '/assessor/': typeof AssessorIndexRoute
  '/assessment/$domain': typeof WorkspaceAssessmentDomainRoute
  '/assessor/$id/context': typeof AssessorIdContextRoute
  '/assessor/$id/evidence': typeof AssessorIdEvidenceRoute
  '/assessor/$id/responses': typeof AssessorIdResponsesRoute
  '/assessor/$id/runs': typeof AssessorIdRunsRoute
  '/assessor/$id/scoring': typeof AssessorIdScoringRoute
  '/assessment/': typeof WorkspaceAssessmentIndexRoute
  '/assessor/$id/': typeof AssessorIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ecri': typeof EcriRoute
  '/login': typeof LoginRoute
  '/evidence': typeof WorkspaceEvidenceRoute
  '/intelligence': typeof WorkspaceIntelligenceRoute
  '/orientation': typeof WorkspaceOrientationRoute
  '/overview': typeof WorkspaceOverviewRoute
  '/profile': typeof WorkspaceProfileRoute
  '/pulse': typeof WorkspacePulseRoute
  '/assessor': typeof AssessorIndexRoute
  '/assessment/$domain': typeof WorkspaceAssessmentDomainRoute
  '/assessor/$id/context': typeof AssessorIdContextRoute
  '/assessor/$id/evidence': typeof AssessorIdEvidenceRoute
  '/assessor/$id/responses': typeof AssessorIdResponsesRoute
  '/assessor/$id/runs': typeof AssessorIdRunsRoute
  '/assessor/$id/scoring': typeof AssessorIdScoringRoute
  '/assessment': typeof WorkspaceAssessmentIndexRoute
  '/assessor/$id': typeof AssessorIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_workspace': typeof WorkspaceRouteWithChildren
  '/admin': typeof AdminRoute
  '/assessor': typeof AssessorRouteWithChildren
  '/ecri': typeof EcriRoute
  '/login': typeof LoginRoute
  '/_workspace/evidence': typeof WorkspaceEvidenceRoute
  '/_workspace/intelligence': typeof WorkspaceIntelligenceRoute
  '/_workspace/orientation': typeof WorkspaceOrientationRoute
  '/_workspace/overview': typeof WorkspaceOverviewRoute
  '/_workspace/profile': typeof WorkspaceProfileRoute
  '/_workspace/pulse': typeof WorkspacePulseRoute
  '/assessor/$id': typeof AssessorIdRouteWithChildren
  '/assessor/': typeof AssessorIndexRoute
  '/_workspace/assessment/$domain': typeof WorkspaceAssessmentDomainRoute
  '/assessor/$id/context': typeof AssessorIdContextRoute
  '/assessor/$id/evidence': typeof AssessorIdEvidenceRoute
  '/assessor/$id/responses': typeof AssessorIdResponsesRoute
  '/assessor/$id/runs': typeof AssessorIdRunsRoute
  '/assessor/$id/scoring': typeof AssessorIdScoringRoute
  '/_workspace/assessment/': typeof WorkspaceAssessmentIndexRoute
  '/assessor/$id/': typeof AssessorIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/assessor'
    | '/ecri'
    | '/login'
    | '/evidence'
    | '/intelligence'
    | '/orientation'
    | '/overview'
    | '/profile'
    | '/pulse'
    | '/assessor/$id'
    | '/assessor/'
    | '/assessment/$domain'
    | '/assessor/$id/context'
    | '/assessor/$id/evidence'
    | '/assessor/$id/responses'
    | '/assessor/$id/runs'
    | '/assessor/$id/scoring'
    | '/assessment/'
    | '/assessor/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ecri'
    | '/login'
    | '/evidence'
    | '/intelligence'
    | '/orientation'
    | '/overview'
    | '/profile'
    | '/pulse'
    | '/assessor'
    | '/assessment/$domain'
    | '/assessor/$id/context'
    | '/assessor/$id/evidence'
    | '/assessor/$id/responses'
    | '/assessor/$id/runs'
    | '/assessor/$id/scoring'
    | '/assessment'
    | '/assessor/$id'
  id:
    | '__root__'
    | '/'
    | '/_workspace'
    | '/admin'
    | '/assessor'
    | '/ecri'
    | '/login'
    | '/_workspace/evidence'
    | '/_workspace/intelligence'
    | '/_workspace/orientation'
    | '/_workspace/overview'
    | '/_workspace/profile'
    | '/_workspace/pulse'
    | '/assessor/$id'
    | '/assessor/'
    | '/_workspace/assessment/$domain'
    | '/assessor/$id/context'
    | '/assessor/$id/evidence'
    | '/assessor/$id/responses'
    | '/assessor/$id/runs'
    | '/assessor/$id/scoring'
    | '/_workspace/assessment/'
    | '/assessor/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  AdminRoute: typeof AdminRoute
  AssessorRoute: typeof AssessorRouteWithChildren
  EcriRoute: typeof EcriRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessor': {
      id: '/assessor'
      path: '/assessor'
      fullPath: '/assessor'
      preLoaderRoute: typeof AssessorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecri': {
      id: '/ecri'
      path: '/ecri'
      fullPath: '/ecri'
      preLoaderRoute: typeof EcriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/evidence': {
      id: '/_workspace/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof WorkspaceEvidenceRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/intelligence': {
      id: '/_workspace/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof WorkspaceIntelligenceRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/orientation': {
      id: '/_workspace/orientation'
      path: '/orientation'
      fullPath: '/orientation'
      preLoaderRoute: typeof WorkspaceOrientationRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/overview': {
      id: '/_workspace/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof WorkspaceOverviewRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/profile': {
      id: '/_workspace/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof WorkspaceProfileRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/pulse': {
      id: '/_workspace/pulse'
      path: '/pulse'
      fullPath: '/pulse'
      preLoaderRoute: typeof WorkspacePulseRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/assessor/': {
      id: '/assessor/'
      path: '/'
      fullPath: '/assessor/'
      preLoaderRoute: typeof AssessorIndexRouteImport
      parentRoute: typeof AssessorRoute
    }
    '/assessor/$id': {
      id: '/assessor/$id'
      path: '/$id'
      fullPath: '/assessor/$id'
      preLoaderRoute: typeof AssessorIdRouteImport
      parentRoute: typeof AssessorRoute
    }
    '/_workspace/assessment/': {
      id: '/_workspace/assessment/'
      path: '/assessment'
      fullPath: '/assessment/'
      preLoaderRoute: typeof WorkspaceAssessmentIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/assessment/$domain': {
      id: '/_workspace/assessment/$domain'
      path: '/assessment/$domain'
      fullPath: '/assessment/$domain'
      preLoaderRoute: typeof WorkspaceAssessmentDomainRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/assessor/$id/': {
      id: '/assessor/$id/'
      path: '/'
      fullPath: '/assessor/$id/'
      preLoaderRoute: typeof AssessorIdIndexRouteImport
      parentRoute: typeof AssessorIdRoute
    }
    '/assessor/$id/context': {
      id: '/assessor/$id/context'
      path: '/context'
      fullPath: '/assessor/$id/context'
      preLoaderRoute: typeof AssessorIdContextRouteImport
      parentRoute: typeof AssessorIdRoute
    }
    '/assessor/$id/evidence': {
      id: '/assessor/$id/evidence'
      path: '/evidence'
      fullPath: '/assessor/$id/evidence'
      preLoaderRoute: typeof AssessorIdEvidenceRouteImport
      parentRoute: typeof AssessorIdRoute
    }
    '/assessor/$id/responses': {
      id: '/assessor/$id/responses'
      path: '/responses'
      fullPath: '/assessor/$id/responses'
      preLoaderRoute: typeof AssessorIdResponsesRouteImport
      parentRoute: typeof AssessorIdRoute
    }
    '/assessor/$id/runs': {
      id: '/assessor/$id/runs'
      path: '/runs'
      fullPath: '/assessor/$id/runs'
      preLoaderRoute: typeof AssessorIdRunsRouteImport
      parentRoute: typeof AssessorIdRoute
    }
    '/assessor/$id/scoring': {
      id: '/assessor/$id/scoring'
      path: '/scoring'
      fullPath: '/assessor/$id/scoring'
      preLoaderRoute: typeof AssessorIdScoringRouteImport
      parentRoute: typeof AssessorIdRoute
    }
  }
}

interface WorkspaceRouteChildren {
  WorkspaceEvidenceRoute: typeof WorkspaceEvidenceRoute
  WorkspaceIntelligenceRoute: typeof WorkspaceIntelligenceRoute
  WorkspaceOrientationRoute: typeof WorkspaceOrientationRoute
  WorkspaceOverviewRoute: typeof WorkspaceOverviewRoute
  WorkspaceProfileRoute: typeof WorkspaceProfileRoute
  WorkspacePulseRoute: typeof WorkspacePulseRoute
  WorkspaceAssessmentDomainRoute: typeof WorkspaceAssessmentDomainRoute
  WorkspaceAssessmentIndexRoute: typeof WorkspaceAssessmentIndexRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceEvidenceRoute: WorkspaceEvidenceRoute,
  WorkspaceIntelligenceRoute: WorkspaceIntelligenceRoute,
  WorkspaceOrientationRoute: WorkspaceOrientationRoute,
  WorkspaceOverviewRoute: WorkspaceOverviewRoute,
  WorkspaceProfileRoute: WorkspaceProfileRoute,
  WorkspacePulseRoute: WorkspacePulseRoute,
  WorkspaceAssessmentDomainRoute: WorkspaceAssessmentDomainRoute,
  WorkspaceAssessmentIndexRoute: WorkspaceAssessmentIndexRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

interface AssessorIdRouteChildren {
  AssessorIdContextRoute: typeof AssessorIdContextRoute
  AssessorIdEvidenceRoute: typeof AssessorIdEvidenceRoute
  AssessorIdResponsesRoute: typeof AssessorIdResponsesRoute
  AssessorIdRunsRoute: typeof AssessorIdRunsRoute
  AssessorIdScoringRoute: typeof AssessorIdScoringRoute
  AssessorIdIndexRoute: typeof AssessorIdIndexRoute
}

const AssessorIdRouteChildren: AssessorIdRouteChildren = {
  AssessorIdContextRoute: AssessorIdContextRoute,
  AssessorIdEvidenceRoute: AssessorIdEvidenceRoute,
  AssessorIdResponsesRoute: AssessorIdResponsesRoute,
  AssessorIdRunsRoute: AssessorIdRunsRoute,
  AssessorIdScoringRoute: AssessorIdScoringRoute,
  AssessorIdIndexRoute: AssessorIdIndexRoute,
}

const AssessorIdRouteWithChildren = AssessorIdRoute._addFileChildren(
  AssessorIdRouteChildren,
)

interface AssessorRouteChildren {
  AssessorIdRoute: typeof AssessorIdRouteWithChildren
  AssessorIndexRoute: typeof AssessorIndexRoute
}

const AssessorRouteChildren: AssessorRouteChildren = {
  AssessorIdRoute: AssessorIdRouteWithChildren,
  AssessorIndexRoute: AssessorIndexRoute,
}

const AssessorRouteWithChildren = AssessorRoute._addFileChildren(
  AssessorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceRoute: WorkspaceRouteWithChildren,
  AdminRoute: AdminRoute,
  AssessorRoute: AssessorRouteWithChildren,
  EcriRoute: EcriRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
