/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceRouteImport } from './routes/_workspace'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AruiRouteImport } from './routes/arui'
import { Route as AssessorRouteImport } from './routes/assessor'
import { Route as EcriRouteImport } from './routes/ecri'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as WorkspaceEvidenceRouteImport } from './routes/_workspace.evidence'
import { Route as WorkspaceIntelligenceRouteImport } from './routes/_workspace.intelligence'
import { Route as WorkspaceOrientationRouteImport } from './routes/_workspace.orientation'
import { Route as WorkspaceOverviewRouteImport } from './routes/_workspace.overview'
import { Route as WorkspaceProfileRouteImport } from './routes/_workspace.profile'
import { Route as WorkspacePulseRouteImport } from './routes/_workspace.pulse'
import { Route as AruiIndexRouteImport } from './routes/arui.index'
import { Route as AruiEvidenceRouteImport } from './routes/arui.evidence'
import { Route as AruiIntelligenceRouteImport } from './routes/arui.intelligence'
import { Route as AruiLoginRouteImport } from './routes/arui.login'
import { Route as AruiOrientationRouteImport } from './routes/arui.orientation'
import { Route as AruiOverviewRouteImport } from './routes/arui.overview'
import { Route as AruiProfileRouteImport } from './routes/arui.profile'
import { Route as AruiPulseRouteImport } from './routes/arui.pulse'
import { Route as AssessorIndexRouteImport } from './routes/assessor.index'
import { Route as AssessorIdRouteImport } from './routes/assessor.$id'
import { Route as EcriIndexRouteImport } from './routes/ecri.index'
import { Route as EcriEngagementRouteImport } from './routes/ecri.engagement'
import { Route as EcriEvidenceRouteImport } from './routes/ecri.evidence'
import { Route as EcriIntelligenceRouteImport } from './routes/ecri.intelligence'
import { Route as EcriLoginRouteImport } from './routes/ecri.login'
import { Route as EcriOrientationRouteImport } from './routes/ecri.orientation'
import { Route as EcriOverviewRouteImport } from './routes/ecri.overview'
import { Route as EcriProfileRouteImport } from './routes/ecri.profile'
import { Route as EcriPulseRouteImport } from './routes/ecri.pulse'
import { Route as WorkspaceAssessmentIndexRouteImport } from './routes/_workspace.assessment.index'
import { Route as WorkspaceAssessmentDomainRouteImport } from './routes/_workspace.assessment.$domain'
import { Route as AruiAssessmentIndexRouteImport } from './routes/arui.assessment.index'
import { Route as AruiAssessmentDomainRouteImport } from './routes/arui.assessment.$domain'
import { Route as AssessorIdIndexRouteImport } from './routes/assessor.$id.index'
import { Route as AssessorIdContextRouteImport } from './routes/assessor.$id.context'
import { Route as AssessorIdEvidenceRouteImport } from './routes/assessor.$id.evidence'
import { Route as AssessorIdResponsesRouteImport } from './routes/assessor.$id.responses'
import { Route as AssessorIdRunsRouteImport } from './routes/assessor.$id.runs'
import { Route as AssessorIdScoringRouteImport } from './routes/assessor.$id.scoring'
import { Route as EcriAssessmentIndexRouteImport } from './routes/ecri.assessment.index'
import { Route as EcriAssessmentDomainRouteImport } from './routes/ecri.assessment.$domain'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AruiRoute = AruiRouteImport.update({
  id: '/arui',
  path: '/arui',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessorRoute = AssessorRouteImport.update({
  id: '/assessor',
  path: '/assessor',
  getParentRoute: () => rootRouteImport,
} as any)
const EcriRoute = EcriRouteImport.update({
  id: '/ecri',
  path: '/ecri',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceEvidenceRoute = WorkspaceEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceIntelligenceRoute = WorkspaceIntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceOrientationRoute = WorkspaceOrientationRouteImport.update({
  id: '/orientation',
  path: '/orientation',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceOverviewRoute = WorkspaceOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceProfileRoute = WorkspaceProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspacePulseRoute = WorkspacePulseRouteImport.update({
  id: '/pulse',
  path: '/pulse',
  getParentRoute: () => WorkspaceRoute,
} as any)
const AruiIndexRoute = AruiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AruiRoute,
} as any)
const AruiEvidenceRoute = AruiEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => AruiRoute,
} as any)
const AruiIntelligenceRoute = AruiIntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => AruiRoute,
} as any)
const AruiLoginRoute = AruiLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AruiRoute,
} as any)
const AruiOrientationRoute = AruiOrientationRouteImport.update({
  id: '/orientation',
  path: '/orientation',
  getParentRoute: () => AruiRoute,
} as any)
const AruiOverviewRoute = AruiOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AruiRoute,
} as any)
const AruiProfileRoute = AruiProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AruiRoute,
} as any)
const AruiPulseRoute = AruiPulseRouteImport.update({
  id: '/pulse',
  path: '/pulse',
  getParentRoute: () => AruiRoute,
} as any)
const AssessorIndexRoute = AssessorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AssessorRoute,
} as any)
const AssessorIdRoute = AssessorIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AssessorRoute,
} as any)
const EcriIndexRoute = EcriIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EcriRoute,
} as any)
const EcriEngagementRoute = EcriEngagementRouteImport.update({
  id: '/engagement',
  path: '/engagement',
  getParentRoute: () => EcriRoute,
} as any)
const EcriEvidenceRoute = EcriEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => EcriRoute,
} as any)
const EcriIntelligenceRoute = EcriIntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => EcriRoute,
} as any)
const EcriLoginRoute = EcriLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => EcriRoute,
} as any)
const EcriOrientationRoute = EcriOrientationRouteImport.update({
  id: '/orientation',
  path: '/orientation',
  getParentRoute: () => EcriRoute,
} as any)
const EcriOverviewRoute = EcriOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => EcriRoute,
} as any)
const EcriProfileRoute = EcriProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => EcriRoute,
} as any)
const EcriPulseRoute = EcriPulseRouteImport.update({
  id: '/pulse',
  path: '/pulse',
  getParentRoute: () => EcriRoute,
} as any)
const WorkspaceAssessmentIndexRoute =
  WorkspaceAssessmentIndexRouteImport.update({
    id: '/assessment/',
    path: '/assessment/',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceAssessmentDomainRoute =
  WorkspaceAssessmentDomainRouteImport.update({
    id: '/assessment/$domain',
    path: '/assessment/$domain',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const AruiAssessmentIndexRoute = AruiAssessmentIndexRouteImport.update({
  id: '/assessment/',
  path: '/assessment/',
  getParentRoute: () => AruiRoute,
} as any)
const AruiAssessmentDomainRoute = AruiAssessmentDomainRouteImport.update({
  id: '/assessment/$domain',
  path: '/assessment/$domain',
  getParentRoute: () => AruiRoute,
} as any)
const AssessorIdIndexRoute = AssessorIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AssessorIdRoute,
} as any)
const AssessorIdContextRoute = AssessorIdContextRouteImport.update({
  id: '/context',
  path: '/context',
  getParentRoute: () => AssessorIdRoute,
} as any)
const AssessorIdEvidenceRoute = AssessorIdEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => AssessorIdRoute,
} as any)
const AssessorIdResponsesRoute = AssessorIdResponsesRouteImport.update({
  id: '/responses',
  path: '/responses',
  getParentRoute: () => AssessorIdRoute,
} as any)
const AssessorIdRunsRoute = AssessorIdRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => AssessorIdRoute,
} as any)
const AssessorIdScoringRoute = AssessorIdScoringRouteImport.update({
  id: '/scoring',
  path: '/scoring',
  getParentRoute: () => AssessorIdRoute,
} as any)
const EcriAssessmentIndexRoute = EcriAssessmentIndexRouteImport.update({
  id: '/assessment/',
  path: '/assessment/',
  getParentRoute: () => EcriRoute,
} as any)
const EcriAssessmentDomainRoute = EcriAssessmentDomainRouteImport.update({
  id: '/assessment/$domain',
  path: '/assessment/$domain',
  getParentRoute: () => EcriRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/arui': typeof AruiRouteWithChildren
  '/assessor': typeof AssessorRouteWithChildren
  '/ecri': typeof EcriRouteWithChildren
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRoute
  '/evidence': typeof WorkspaceEvidenceRoute
  '/intelligence': typeof WorkspaceIntelligenceRoute
  '/orientation': typeof WorkspaceOrientationRoute
  '/overview': typeof WorkspaceOverviewRoute
  '/profile': typeof WorkspaceProfileRoute
  '/pulse': typeof WorkspacePulseRoute
  '/arui/evidence': typeof AruiEvidenceRoute
  '/arui/intelligence': typeof AruiIntelligenceRoute
  '/arui/login': typeof AruiLoginRoute
  '/arui/orientation': typeof AruiOrientationRoute
  '/arui/overview': typeof AruiOverviewRoute
  '/arui/profile': typeof AruiProfileRoute
  '/arui/pulse': typeof AruiPulseRoute
  '/assessor/$id': typeof AssessorIdRouteWithChildren
  '/ecri/engagement': typeof EcriEngagementRoute
  '/ecri/evidence': typeof EcriEvidenceRoute
  '/ecri/intelligence': typeof EcriIntelligenceRoute
  '/ecri/login': typeof EcriLoginRoute
  '/ecri/orientation': typeof EcriOrientationRoute
  '/ecri/overview': typeof EcriOverviewRoute
  '/ecri/profile': typeof EcriProfileRoute
  '/ecri/pulse': typeof EcriPulseRoute
  '/arui/': typeof AruiIndexRoute
  '/assessor/': typeof AssessorIndexRoute
  '/ecri/': typeof EcriIndexRoute
  '/assessment/$domain': typeof WorkspaceAssessmentDomainRoute
  '/arui/assessment/$domain': typeof AruiAssessmentDomainRoute
  '/assessor/$id/context': typeof AssessorIdContextRoute
  '/assessor/$id/evidence': typeof AssessorIdEvidenceRoute
  '/assessor/$id/responses': typeof AssessorIdResponsesRoute
  '/assessor/$id/runs': typeof AssessorIdRunsRoute
  '/assessor/$id/scoring': typeof AssessorIdScoringRoute
  '/ecri/assessment/$domain': typeof EcriAssessmentDomainRoute
  '/assessment/': typeof WorkspaceAssessmentIndexRoute
  '/arui/assessment/': typeof AruiAssessmentIndexRoute
  '/assessor/$id/': typeof AssessorIdIndexRoute
  '/ecri/assessment/': typeof EcriAssessmentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRoute
  '/evidence': typeof WorkspaceEvidenceRoute
  '/intelligence': typeof WorkspaceIntelligenceRoute
  '/orientation': typeof WorkspaceOrientationRoute
  '/overview': typeof WorkspaceOverviewRoute
  '/profile': typeof WorkspaceProfileRoute
  '/pulse': typeof WorkspacePulseRoute
  '/arui/evidence': typeof AruiEvidenceRoute
  '/arui/intelligence': typeof AruiIntelligenceRoute
  '/arui/login': typeof AruiLoginRoute
  '/arui/orientation': typeof AruiOrientationRoute
  '/arui/overview': typeof AruiOverviewRoute
  '/arui/profile': typeof AruiProfileRoute
  '/arui/pulse': typeof AruiPulseRoute
  '/ecri/engagement': typeof EcriEngagementRoute
  '/ecri/evidence': typeof EcriEvidenceRoute
  '/ecri/intelligence': typeof EcriIntelligenceRoute
  '/ecri/login': typeof EcriLoginRoute
  '/ecri/orientation': typeof EcriOrientationRoute
  '/ecri/overview': typeof EcriOverviewRoute
  '/ecri/profile': typeof EcriProfileRoute
  '/ecri/pulse': typeof EcriPulseRoute
  '/arui': typeof AruiIndexRoute
  '/assessor': typeof AssessorIndexRoute
  '/ecri': typeof EcriIndexRoute
  '/assessment/$domain': typeof WorkspaceAssessmentDomainRoute
  '/arui/assessment/$domain': typeof AruiAssessmentDomainRoute
  '/assessor/$id/context': typeof AssessorIdContextRoute
  '/assessor/$id/evidence': typeof AssessorIdEvidenceRoute
  '/assessor/$id/responses': typeof AssessorIdResponsesRoute
  '/assessor/$id/runs': typeof AssessorIdRunsRoute
  '/assessor/$id/scoring': typeof AssessorIdScoringRoute
  '/ecri/assessment/$domain': typeof EcriAssessmentDomainRoute
  '/assessment': typeof WorkspaceAssessmentIndexRoute
  '/arui/assessment': typeof AruiAssessmentIndexRoute
  '/assessor/$id': typeof AssessorIdIndexRoute
  '/ecri/assessment': typeof EcriAssessmentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_workspace': typeof WorkspaceRouteWithChildren
  '/admin': typeof AdminRoute
  '/arui': typeof AruiRouteWithChildren
  '/assessor': typeof AssessorRouteWithChildren
  '/ecri': typeof EcriRouteWithChildren
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRoute
  '/_workspace/evidence': typeof WorkspaceEvidenceRoute
  '/_workspace/intelligence': typeof WorkspaceIntelligenceRoute
  '/_workspace/orientation': typeof WorkspaceOrientationRoute
  '/_workspace/overview': typeof WorkspaceOverviewRoute
  '/_workspace/profile': typeof WorkspaceProfileRoute
  '/_workspace/pulse': typeof WorkspacePulseRoute
  '/arui/evidence': typeof AruiEvidenceRoute
  '/arui/intelligence': typeof AruiIntelligenceRoute
  '/arui/login': typeof AruiLoginRoute
  '/arui/orientation': typeof AruiOrientationRoute
  '/arui/overview': typeof AruiOverviewRoute
  '/arui/profile': typeof AruiProfileRoute
  '/arui/pulse': typeof AruiPulseRoute
  '/assessor/$id': typeof AssessorIdRouteWithChildren
  '/ecri/engagement': typeof EcriEngagementRoute
  '/ecri/evidence': typeof EcriEvidenceRoute
  '/ecri/intelligence': typeof EcriIntelligenceRoute
  '/ecri/login': typeof EcriLoginRoute
  '/ecri/orientation': typeof EcriOrientationRoute
  '/ecri/overview': typeof EcriOverviewRoute
  '/ecri/profile': typeof EcriProfileRoute
  '/ecri/pulse': typeof EcriPulseRoute
  '/arui/': typeof AruiIndexRoute
  '/assessor/': typeof AssessorIndexRoute
  '/ecri/': typeof EcriIndexRoute
  '/_workspace/assessment/$domain': typeof WorkspaceAssessmentDomainRoute
  '/arui/assessment/$domain': typeof AruiAssessmentDomainRoute
  '/assessor/$id/context': typeof AssessorIdContextRoute
  '/assessor/$id/evidence': typeof AssessorIdEvidenceRoute
  '/assessor/$id/responses': typeof AssessorIdResponsesRoute
  '/assessor/$id/runs': typeof AssessorIdRunsRoute
  '/assessor/$id/scoring': typeof AssessorIdScoringRoute
  '/ecri/assessment/$domain': typeof EcriAssessmentDomainRoute
  '/_workspace/assessment/': typeof WorkspaceAssessmentIndexRoute
  '/arui/assessment/': typeof AruiAssessmentIndexRoute
  '/assessor/$id/': typeof AssessorIdIndexRoute
  '/ecri/assessment/': typeof EcriAssessmentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/arui'
    | '/assessor'
    | '/ecri'
    | '/login'
    | '/portfolio'
    | '/evidence'
    | '/intelligence'
    | '/orientation'
    | '/overview'
    | '/profile'
    | '/pulse'
    | '/arui/evidence'
    | '/arui/intelligence'
    | '/arui/login'
    | '/arui/orientation'
    | '/arui/overview'
    | '/arui/profile'
    | '/arui/pulse'
    | '/assessor/$id'
    | '/ecri/engagement'
    | '/ecri/evidence'
    | '/ecri/intelligence'
    | '/ecri/login'
    | '/ecri/orientation'
    | '/ecri/overview'
    | '/ecri/profile'
    | '/ecri/pulse'
    | '/arui/'
    | '/assessor/'
    | '/ecri/'
    | '/assessment/$domain'
    | '/arui/assessment/$domain'
    | '/assessor/$id/context'
    | '/assessor/$id/evidence'
    | '/assessor/$id/responses'
    | '/assessor/$id/runs'
    | '/assessor/$id/scoring'
    | '/ecri/assessment/$domain'
    | '/assessment/'
    | '/arui/assessment/'
    | '/assessor/$id/'
    | '/ecri/assessment/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/portfolio'
    | '/evidence'
    | '/intelligence'
    | '/orientation'
    | '/overview'
    | '/profile'
    | '/pulse'
    | '/arui/evidence'
    | '/arui/intelligence'
    | '/arui/login'
    | '/arui/orientation'
    | '/arui/overview'
    | '/arui/profile'
    | '/arui/pulse'
    | '/ecri/engagement'
    | '/ecri/evidence'
    | '/ecri/intelligence'
    | '/ecri/login'
    | '/ecri/orientation'
    | '/ecri/overview'
    | '/ecri/profile'
    | '/ecri/pulse'
    | '/arui'
    | '/assessor'
    | '/ecri'
    | '/assessment/$domain'
    | '/arui/assessment/$domain'
    | '/assessor/$id/context'
    | '/assessor/$id/evidence'
    | '/assessor/$id/responses'
    | '/assessor/$id/runs'
    | '/assessor/$id/scoring'
    | '/ecri/assessment/$domain'
    | '/assessment'
    | '/arui/assessment'
    | '/assessor/$id'
    | '/ecri/assessment'
  id:
    | '__root__'
    | '/'
    | '/_workspace'
    | '/admin'
    | '/arui'
    | '/assessor'
    | '/ecri'
    | '/login'
    | '/portfolio'
    | '/_workspace/evidence'
    | '/_workspace/intelligence'
    | '/_workspace/orientation'
    | '/_workspace/overview'
    | '/_workspace/profile'
    | '/_workspace/pulse'
    | '/arui/evidence'
    | '/arui/intelligence'
    | '/arui/login'
    | '/arui/orientation'
    | '/arui/overview'
    | '/arui/profile'
    | '/arui/pulse'
    | '/assessor/$id'
    | '/ecri/engagement'
    | '/ecri/evidence'
    | '/ecri/intelligence'
    | '/ecri/login'
    | '/ecri/orientation'
    | '/ecri/overview'
    | '/ecri/profile'
    | '/ecri/pulse'
    | '/arui/'
    | '/assessor/'
    | '/ecri/'
    | '/_workspace/assessment/$domain'
    | '/arui/assessment/$domain'
    | '/assessor/$id/context'
    | '/assessor/$id/evidence'
    | '/assessor/$id/responses'
    | '/assessor/$id/runs'
    | '/assessor/$id/scoring'
    | '/ecri/assessment/$domain'
    | '/_workspace/assessment/'
    | '/arui/assessment/'
    | '/assessor/$id/'
    | '/ecri/assessment/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  AdminRoute: typeof AdminRoute
  AruiRoute: typeof AruiRouteWithChildren
  AssessorRoute: typeof AssessorRouteWithChildren
  EcriRoute: typeof EcriRouteWithChildren
  LoginRoute: typeof LoginRoute
  PortfolioRoute: typeof PortfolioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arui': {
      id: '/arui'
      path: '/arui'
      fullPath: '/arui'
      preLoaderRoute: typeof AruiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessor': {
      id: '/assessor'
      path: '/assessor'
      fullPath: '/assessor'
      preLoaderRoute: typeof AssessorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecri': {
      id: '/ecri'
      path: '/ecri'
      fullPath: '/ecri'
      preLoaderRoute: typeof EcriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/evidence': {
      id: '/_workspace/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof WorkspaceEvidenceRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/intelligence': {
      id: '/_workspace/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof WorkspaceIntelligenceRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/orientation': {
      id: '/_workspace/orientation'
      path: '/orientation'
      fullPath: '/orientation'
      preLoaderRoute: typeof WorkspaceOrientationRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/overview': {
      id: '/_workspace/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof WorkspaceOverviewRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/profile': {
      id: '/_workspace/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof WorkspaceProfileRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/pulse': {
      id: '/_workspace/pulse'
      path: '/pulse'
      fullPath: '/pulse'
      preLoaderRoute: typeof WorkspacePulseRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/arui/': {
      id: '/arui/'
      path: '/'
      fullPath: '/arui/'
      preLoaderRoute: typeof AruiIndexRouteImport
      parentRoute: typeof AruiRoute
    }
    '/arui/evidence': {
      id: '/arui/evidence'
      path: '/evidence'
      fullPath: '/arui/evidence'
      preLoaderRoute: typeof AruiEvidenceRouteImport
      parentRoute: typeof AruiRoute
    }
    '/arui/intelligence': {
      id: '/arui/intelligence'
      path: '/intelligence'
      fullPath: '/arui/intelligence'
      preLoaderRoute: typeof AruiIntelligenceRouteImport
      parentRoute: typeof AruiRoute
    }
    '/arui/login': {
      id: '/arui/login'
      path: '/login'
      fullPath: '/arui/login'
      preLoaderRoute: typeof AruiLoginRouteImport
      parentRoute: typeof AruiRoute
    }
    '/arui/orientation': {
      id: '/arui/orientation'
      path: '/orientation'
      fullPath: '/arui/orientation'
      preLoaderRoute: typeof AruiOrientationRouteImport
      parentRoute: typeof AruiRoute
    }
    '/arui/overview': {
      id: '/arui/overview'
      path: '/overview'
      fullPath: '/arui/overview'
      preLoaderRoute: typeof AruiOverviewRouteImport
      parentRoute: typeof AruiRoute
    }
    '/arui/profile': {
      id: '/arui/profile'
      path: '/profile'
      fullPath: '/arui/profile'
      preLoaderRoute: typeof AruiProfileRouteImport
      parentRoute: typeof AruiRoute
    }
    '/arui/pulse': {
      id: '/arui/pulse'
      path: '/pulse'
      fullPath: '/arui/pulse'
      preLoaderRoute: typeof AruiPulseRouteImport
      parentRoute: typeof AruiRoute
    }
    '/assessor/': {
      id: '/assessor/'
      path: '/'
      fullPath: '/assessor/'
      preLoaderRoute: typeof AssessorIndexRouteImport
      parentRoute: typeof AssessorRoute
    }
    '/assessor/$id': {
      id: '/assessor/$id'
      path: '/$id'
      fullPath: '/assessor/$id'
      preLoaderRoute: typeof AssessorIdRouteImport
      parentRoute: typeof AssessorRoute
    }
    '/ecri/': {
      id: '/ecri/'
      path: '/'
      fullPath: '/ecri/'
      preLoaderRoute: typeof EcriIndexRouteImport
      parentRoute: typeof EcriRoute
    }
    '/ecri/engagement': {
      id: '/ecri/engagement'
      path: '/engagement'
      fullPath: '/ecri/engagement'
      preLoaderRoute: typeof EcriEngagementRouteImport
      parentRoute: typeof EcriRoute
    }
    '/ecri/evidence': {
      id: '/ecri/evidence'
      path: '/evidence'
      fullPath: '/ecri/evidence'
      preLoaderRoute: typeof EcriEvidenceRouteImport
      parentRoute: typeof EcriRoute
    }
    '/ecri/intelligence': {
      id: '/ecri/intelligence'
      path: '/intelligence'
      fullPath: '/ecri/intelligence'
      preLoaderRoute: typeof EcriIntelligenceRouteImport
      parentRoute: typeof EcriRoute
    }
    '/ecri/login': {
      id: '/ecri/login'
      path: '/login'
      fullPath: '/ecri/login'
      preLoaderRoute: typeof EcriLoginRouteImport
      parentRoute: typeof EcriRoute
    }
    '/ecri/orientation': {
      id: '/ecri/orientation'
      path: '/orientation'
      fullPath: '/ecri/orientation'
      preLoaderRoute: typeof EcriOrientationRouteImport
      parentRoute: typeof EcriRoute
    }
    '/ecri/overview': {
      id: '/ecri/overview'
      path: '/overview'
      fullPath: '/ecri/overview'
      preLoaderRoute: typeof EcriOverviewRouteImport
      parentRoute: typeof EcriRoute
    }
    '/ecri/profile': {
      id: '/ecri/profile'
      path: '/profile'
      fullPath: '/ecri/profile'
      preLoaderRoute: typeof EcriProfileRouteImport
      parentRoute: typeof EcriRoute
    }
    '/ecri/pulse': {
      id: '/ecri/pulse'
      path: '/pulse'
      fullPath: '/ecri/pulse'
      preLoaderRoute: typeof EcriPulseRouteImport
      parentRoute: typeof EcriRoute
    }
    '/_workspace/assessment/': {
      id: '/_workspace/assessment/'
      path: '/assessment'
      fullPath: '/assessment/'
      preLoaderRoute: typeof WorkspaceAssessmentIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/assessment/$domain': {
      id: '/_workspace/assessment/$domain'
      path: '/assessment/$domain'
      fullPath: '/assessment/$domain'
      preLoaderRoute: typeof WorkspaceAssessmentDomainRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/arui/assessment/': {
      id: '/arui/assessment/'
      path: '/assessment'
      fullPath: '/arui/assessment/'
      preLoaderRoute: typeof AruiAssessmentIndexRouteImport
      parentRoute: typeof AruiRoute
    }
    '/arui/assessment/$domain': {
      id: '/arui/assessment/$domain'
      path: '/assessment/$domain'
      fullPath: '/arui/assessment/$domain'
      preLoaderRoute: typeof AruiAssessmentDomainRouteImport
      parentRoute: typeof AruiRoute
    }
    '/assessor/$id/': {
      id: '/assessor/$id/'
      path: '/'
      fullPath: '/assessor/$id/'
      preLoaderRoute: typeof AssessorIdIndexRouteImport
      parentRoute: typeof AssessorIdRoute
    }
    '/assessor/$id/context': {
      id: '/assessor/$id/context'
      path: '/context'
      fullPath: '/assessor/$id/context'
      preLoaderRoute: typeof AssessorIdContextRouteImport
      parentRoute: typeof AssessorIdRoute
    }
    '/assessor/$id/evidence': {
      id: '/assessor/$id/evidence'
      path: '/evidence'
      fullPath: '/assessor/$id/evidence'
      preLoaderRoute: typeof AssessorIdEvidenceRouteImport
      parentRoute: typeof AssessorIdRoute
    }
    '/assessor/$id/responses': {
      id: '/assessor/$id/responses'
      path: '/responses'
      fullPath: '/assessor/$id/responses'
      preLoaderRoute: typeof AssessorIdResponsesRouteImport
      parentRoute: typeof AssessorIdRoute
    }
    '/assessor/$id/runs': {
      id: '/assessor/$id/runs'
      path: '/runs'
      fullPath: '/assessor/$id/runs'
      preLoaderRoute: typeof AssessorIdRunsRouteImport
      parentRoute: typeof AssessorIdRoute
    }
    '/assessor/$id/scoring': {
      id: '/assessor/$id/scoring'
      path: '/scoring'
      fullPath: '/assessor/$id/scoring'
      preLoaderRoute: typeof AssessorIdScoringRouteImport
      parentRoute: typeof AssessorIdRoute
    }
    '/ecri/assessment/': {
      id: '/ecri/assessment/'
      path: '/assessment'
      fullPath: '/ecri/assessment/'
      preLoaderRoute: typeof EcriAssessmentIndexRouteImport
      parentRoute: typeof EcriRoute
    }
    '/ecri/assessment/$domain': {
      id: '/ecri/assessment/$domain'
      path: '/assessment/$domain'
      fullPath: '/ecri/assessment/$domain'
      preLoaderRoute: typeof EcriAssessmentDomainRouteImport
      parentRoute: typeof EcriRoute
    }
  }
}

interface WorkspaceRouteChildren {
  WorkspaceEvidenceRoute: typeof WorkspaceEvidenceRoute
  WorkspaceIntelligenceRoute: typeof WorkspaceIntelligenceRoute
  WorkspaceOrientationRoute: typeof WorkspaceOrientationRoute
  WorkspaceOverviewRoute: typeof WorkspaceOverviewRoute
  WorkspaceProfileRoute: typeof WorkspaceProfileRoute
  WorkspacePulseRoute: typeof WorkspacePulseRoute
  WorkspaceAssessmentDomainRoute: typeof WorkspaceAssessmentDomainRoute
  WorkspaceAssessmentIndexRoute: typeof WorkspaceAssessmentIndexRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceEvidenceRoute: WorkspaceEvidenceRoute,
  WorkspaceIntelligenceRoute: WorkspaceIntelligenceRoute,
  WorkspaceOrientationRoute: WorkspaceOrientationRoute,
  WorkspaceOverviewRoute: WorkspaceOverviewRoute,
  WorkspaceProfileRoute: WorkspaceProfileRoute,
  WorkspacePulseRoute: WorkspacePulseRoute,
  WorkspaceAssessmentDomainRoute: WorkspaceAssessmentDomainRoute,
  WorkspaceAssessmentIndexRoute: WorkspaceAssessmentIndexRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

interface AruiRouteChildren {
  AruiEvidenceRoute: typeof AruiEvidenceRoute
  AruiIntelligenceRoute: typeof AruiIntelligenceRoute
  AruiLoginRoute: typeof AruiLoginRoute
  AruiOrientationRoute: typeof AruiOrientationRoute
  AruiOverviewRoute: typeof AruiOverviewRoute
  AruiProfileRoute: typeof AruiProfileRoute
  AruiPulseRoute: typeof AruiPulseRoute
  AruiIndexRoute: typeof AruiIndexRoute
  AruiAssessmentDomainRoute: typeof AruiAssessmentDomainRoute
  AruiAssessmentIndexRoute: typeof AruiAssessmentIndexRoute
}

const AruiRouteChildren: AruiRouteChildren = {
  AruiEvidenceRoute: AruiEvidenceRoute,
  AruiIntelligenceRoute: AruiIntelligenceRoute,
  AruiLoginRoute: AruiLoginRoute,
  AruiOrientationRoute: AruiOrientationRoute,
  AruiOverviewRoute: AruiOverviewRoute,
  AruiProfileRoute: AruiProfileRoute,
  AruiPulseRoute: AruiPulseRoute,
  AruiIndexRoute: AruiIndexRoute,
  AruiAssessmentDomainRoute: AruiAssessmentDomainRoute,
  AruiAssessmentIndexRoute: AruiAssessmentIndexRoute,
}

const AruiRouteWithChildren = AruiRoute._addFileChildren(AruiRouteChildren)

interface AssessorIdRouteChildren {
  AssessorIdContextRoute: typeof AssessorIdContextRoute
  AssessorIdEvidenceRoute: typeof AssessorIdEvidenceRoute
  AssessorIdResponsesRoute: typeof AssessorIdResponsesRoute
  AssessorIdRunsRoute: typeof AssessorIdRunsRoute
  AssessorIdScoringRoute: typeof AssessorIdScoringRoute
  AssessorIdIndexRoute: typeof AssessorIdIndexRoute
}

const AssessorIdRouteChildren: AssessorIdRouteChildren = {
  AssessorIdContextRoute: AssessorIdContextRoute,
  AssessorIdEvidenceRoute: AssessorIdEvidenceRoute,
  AssessorIdResponsesRoute: AssessorIdResponsesRoute,
  AssessorIdRunsRoute: AssessorIdRunsRoute,
  AssessorIdScoringRoute: AssessorIdScoringRoute,
  AssessorIdIndexRoute: AssessorIdIndexRoute,
}

const AssessorIdRouteWithChildren = AssessorIdRoute._addFileChildren(
  AssessorIdRouteChildren,
)

interface AssessorRouteChildren {
  AssessorIdRoute: typeof AssessorIdRouteWithChildren
  AssessorIndexRoute: typeof AssessorIndexRoute
}

const AssessorRouteChildren: AssessorRouteChildren = {
  AssessorIdRoute: AssessorIdRouteWithChildren,
  AssessorIndexRoute: AssessorIndexRoute,
}

const AssessorRouteWithChildren = AssessorRoute._addFileChildren(
  AssessorRouteChildren,
)

interface EcriRouteChildren {
  EcriEngagementRoute: typeof EcriEngagementRoute
  EcriEvidenceRoute: typeof EcriEvidenceRoute
  EcriIntelligenceRoute: typeof EcriIntelligenceRoute
  EcriLoginRoute: typeof EcriLoginRoute
  EcriOrientationRoute: typeof EcriOrientationRoute
  EcriOverviewRoute: typeof EcriOverviewRoute
  EcriProfileRoute: typeof EcriProfileRoute
  EcriPulseRoute: typeof EcriPulseRoute
  EcriIndexRoute: typeof EcriIndexRoute
  EcriAssessmentDomainRoute: typeof EcriAssessmentDomainRoute
  EcriAssessmentIndexRoute: typeof EcriAssessmentIndexRoute
}

const EcriRouteChildren: EcriRouteChildren = {
  EcriEngagementRoute: EcriEngagementRoute,
  EcriEvidenceRoute: EcriEvidenceRoute,
  EcriIntelligenceRoute: EcriIntelligenceRoute,
  EcriLoginRoute: EcriLoginRoute,
  EcriOrientationRoute: EcriOrientationRoute,
  EcriOverviewRoute: EcriOverviewRoute,
  EcriProfileRoute: EcriProfileRoute,
  EcriPulseRoute: EcriPulseRoute,
  EcriIndexRoute: EcriIndexRoute,
  EcriAssessmentDomainRoute: EcriAssessmentDomainRoute,
  EcriAssessmentIndexRoute: EcriAssessmentIndexRoute,
}

const EcriRouteWithChildren = EcriRoute._addFileChildren(EcriRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceRoute: WorkspaceRouteWithChildren,
  AdminRoute: AdminRoute,
  AruiRoute: AruiRouteWithChildren,
  AssessorRoute: AssessorRouteWithChildren,
  EcriRoute: EcriRouteWithChildren,
  LoginRoute: LoginRoute,
  PortfolioRoute: PortfolioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
